var airports = {
"type": "FeatureCollection",
"features": [
{ "type": "Feature", "id": 0, "properties": { "ID": "CEF", "TOWN": "CHICOPEE", "AIRPORT_NA": "WESTOVER\/METROPOLITAN", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 2, "LATITUDE": "42 11 52", "LONGITUDE": "72 31 50", "ELEVATION": 245, "P_LENGTH": 11600.000000, "S_LENGTH": 7050, "P_WIDTH": 300, "S_WIDTH": 150, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "HIRLS", "CONTROLTOW": "MILITARY", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -72.530133, 42.197873 ] } }
,
{ "type": "Feature", "id": 1, "properties": { "ID": "2B2", "TOWN": "NEWBURYPORT", "AIRPORT_NA": "PLUM ISLAND", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 47 45", "LONGITUDE": "70 50 30", "ELEVATION": 11, "P_LENGTH": 2105.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "UNKNOWN", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.841194, 42.795922 ] } }
,
{ "type": "Feature", "id": 2, "properties": { "ID": "BAF", "TOWN": "WESTFIELD", "AIRPORT_NA": "BARNES MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 2, "LATITUDE": "42 09 28", "LONGITUDE": "72 42 58", "ELEVATION": 271, "P_LENGTH": 9000.000000, "S_LENGTH": 5000, "P_WIDTH": 150, "S_WIDTH": 100, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "Y", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -72.715640, 42.157872 ] } }
,
{ "type": "Feature", "id": 3, "properties": { "ID": "6MA0", "TOWN": "AMESBURY", "AIRPORT_NA": "MEADOWBROOK", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 51 36", "LONGITUDE": "70 59 48", "ELEVATION": 117, "P_LENGTH": 2000.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "N", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.996666, 42.861171 ] } }
,
{ "type": "Feature", "id": 4, "properties": { "ID": "15MA", "TOWN": "GOSNOLD", "AIRPORT_NA": "CANAPITSIT", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 25 20", "LONGITUDE": "70 54 34", "ELEVATION": 10, "P_LENGTH": 700.000000, "S_LENGTH": 0, "P_WIDTH": 20, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.909813, 41.422773 ] } }
,
{ "type": "Feature", "id": 5, "properties": { "ID": "04MA", "TOWN": "HAVERHILL", "AIRPORT_NA": "GODDARD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 48 35", "LONGITUDE": "71 08 21", "ELEVATION": 200, "P_LENGTH": 2100.000000, "S_LENGTH": 0, "P_WIDTH": 300, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.139818, 42.810256 ] } }
,
{ "type": "Feature", "id": 6, "properties": { "ID": "5MA3", "TOWN": "WEST BROOKFIELD", "AIRPORT_NA": "PASPORT", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 11 15", "LONGITUDE": "72 08 35", "ELEVATION": 1010, "P_LENGTH": 1800.000000, "S_LENGTH": 0, "P_WIDTH": 60, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.143060, 42.187319 ] } }
,
{ "type": "Feature", "id": 7, "properties": { "ID": "BOS", "TOWN": "BOSTON", "AIRPORT_NA": "LOGAN INTERNATIONAL AIRPORT", "OWNER_TYPE": "MassPort", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 5, "LATITUDE": "42 21 51", "LONGITUDE": "71 00 21", "ELEVATION": 20, "P_LENGTH": 10081.000000, "S_LENGTH": 10005, "P_WIDTH": 150, "S_WIDTH": 150, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT-GROOVED", "P_RUNWAYLI": "YES", "S_RUNWAYLI": "HIRLS", "CONTROLTOW": "FAA", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -71.011782, 42.367204 ] } }
,
{ "type": "Feature", "id": 8, "properties": { "ID": "ACK", "TOWN": "NANTUCKET", "AIRPORT_NA": "NANTUCKET MEMORIAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 3, "LATITUDE": "41 15 11", "LONGITUDE": "70 03 39", "ELEVATION": 48, "P_LENGTH": 6303.000000, "S_LENGTH": 4000, "P_WIDTH": 150, "S_WIDTH": 100, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "FAA", "RESTAURANT": "Y", "RENTALCAR": "N", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -70.062654, 41.256171 ] } }
,
{ "type": "Feature", "id": 9, "properties": { "ID": "CQX", "TOWN": "CHATHAM", "AIRPORT_NA": "CHATHAM MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-1", "RUNWAY": 1, "LATITUDE": "41 41 15", "LONGITUDE": "69 59 15", "ELEVATION": 68, "P_LENGTH": 3001.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -69.990217, 41.688456 ] } }
,
{ "type": "Feature", "id": 10, "properties": { "ID": "OWD", "TOWN": "NORWOOD", "AIRPORT_NA": "NORWOOD MEMORIAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-2", "RUNWAY": 2, "LATITUDE": "42 11 27", "LONGITUDE": "71 10 25", "ELEVATION": 50, "P_LENGTH": 4007.000000, "S_LENGTH": 4001, "P_WIDTH": 150, "S_WIDTH": 75, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "N", "SERVICELEV": "RELIEVER GA", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.175646, 42.190179 ] } }
,
{ "type": "Feature", "id": 11, "properties": { "ID": "EWB", "TOWN": "NEW BEDFORD", "AIRPORT_NA": "NEW BEDFORD REGIONAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 2, "LATITUDE": "41 40 35", "LONGITUDE": "70 57 30", "ELEVATION": 80, "P_LENGTH": 4997.000000, "S_LENGTH": 5000, "P_WIDTH": 150, "S_WIDTH": 150, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.958019, 41.675166 ] } }
,
{ "type": "Feature", "id": 12, "properties": { "ID": "0B5", "TOWN": "MONTAQUE", "AIRPORT_NA": "TURNERS FALLS", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-1", "RUNWAY": 1, "LATITUDE": "42 35 30", "LONGITUDE": "72 31 25", "ELEVATION": 356, "P_LENGTH": 3013.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.523455, 42.591907 ] } }
,
{ "type": "Feature", "id": 13, "properties": { "ID": "FIT", "TOWN": "FITCHBURG", "AIRPORT_NA": "FITCHBURG MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 2, "LATITUDE": "42 33 15", "LONGITUDE": "71 45 33", "ELEVATION": 348, "P_LENGTH": 4511.000000, "S_LENGTH": 3502, "P_WIDTH": 100, "S_WIDTH": 150, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "N", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.757847, 42.554016 ] } }
,
{ "type": "Feature", "id": 14, "properties": { "ID": "AQW", "TOWN": "NORTH ADAMS", "AIRPORT_NA": "HARRIMAN-AND-WEST", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-2", "RUNWAY": 1, "LATITUDE": "42 41 45", "LONGITUDE": "73 10 15", "ELEVATION": 654, "P_LENGTH": 4300.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -73.165608, 42.695905 ] } }
,
{ "type": "Feature", "id": 15, "properties": { "ID": "MA86", "TOWN": "WINDSOR", "AIRPORT_NA": "KENDALLS LANDING AREA", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 30 20", "LONGITUDE": "73 03 35", "ELEVATION": 2102, "P_LENGTH": 1800.000000, "S_LENGTH": 0, "P_WIDTH": 150, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -73.060651, 42.505785 ] } }
,
{ "type": "Feature", "id": 16, "properties": { "ID": "GBR", "TOWN": "GREAT BARRINGTON", "AIRPORT_NA": "GREAT BARRINGTON", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "BU-2", "RUNWAY": 1, "LATITUDE": "42 11 02", "LONGITUDE": "73 24 10", "ELEVATION": 739, "P_LENGTH": 2580.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -73.406000, 42.184451 ] } }
,
{ "type": "Feature", "id": 17, "properties": { "ID": "3MA2", "TOWN": "MIDDLEFIELD", "AIRPORT_NA": "BAINES", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 18 58", "LONGITUDE": "73 01 55", "ELEVATION": 1160, "P_LENGTH": 2200.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -73.031962, 42.318283 ] } }
,
{ "type": "Feature", "id": 18, "properties": { "ID": "MA77", "TOWN": "WASHINGTON", "AIRPORT_NA": "BLUEBERRY HILL", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 22 30", "LONGITUDE": "73 08 51", "ELEVATION": 2000, "P_LENGTH": 1800.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -73.147927, 42.375291 ] } }
,
{ "type": "Feature", "id": 19, "properties": { "ID": "MA88", "TOWN": "ALBERT FARMS", "AIRPORT_NA": "WORTHINGTON", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 23 24", "LONGITUDE": "72 55 51", "ELEVATION": 1425, "P_LENGTH": 2800.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "ASPHALT\/GRAVEL", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.932616, 42.392010 ] } }
,
{ "type": "Feature", "id": 20, "properties": { "ID": "PSF", "TOWN": "PITTSFIELD", "AIRPORT_NA": "PITTSFIELD MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 2, "LATITUDE": "42 25 36", "LONGITUDE": "73 17 36", "ELEVATION": 1194, "P_LENGTH": 5001.000000, "S_LENGTH": 3496, "P_WIDTH": 100, "S_WIDTH": 100, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -73.292086, 42.427395 ] } }
,
{ "type": "Feature", "id": 21, "properties": { "ID": "MA43", "TOWN": "GRANVILLE", "AIRPORT_NA": "MOREHAVEN", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 04 20", "LONGITUDE": "72 54 00", "ELEVATION": 1120, "P_LENGTH": 1170.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.900266, 42.072137 ] } }
,
{ "type": "Feature", "id": 22, "properties": { "ID": "28MA", "TOWN": "SOUTHWICK", "AIRPORT_NA": "CANNIZZARO FIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 04 47", "LONGITUDE": "72 49 05", "ELEVATION": 250, "P_LENGTH": 1600.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.818696, 42.078432 ] } }
,
{ "type": "Feature", "id": 23, "properties": { "ID": "MA80", "TOWN": "WESTFIELD", "AIRPORT_NA": "MUNDALE", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 07 11", "LONGITUDE": "72 48 51", "ELEVATION": 280, "P_LENGTH": 1600.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.815838, 42.122045 ] } }
,
{ "type": "Feature", "id": 24, "properties": { "ID": "7B2", "TOWN": "NORTHAMPTON", "AIRPORT_NA": "NORTHAMPTON", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "BU-2", "RUNWAY": 1, "LATITUDE": "42 19 41", "LONGITUDE": "72 36 42", "ELEVATION": 122, "P_LENGTH": 3365.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "NON-STANDARD", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.613127, 42.329099 ] } }
,
{ "type": "Feature", "id": 25, "properties": { "ID": "03MA", "TOWN": "HADLEY", "AIRPORT_NA": "HADLEY", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 23 35", "LONGITUDE": "72 33 07", "ELEVATION": 1600, "P_LENGTH": 0.000000, "S_LENGTH": 60, "P_WIDTH": 0, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.551241, 42.392883 ] } }
,
{ "type": "Feature", "id": 26, "properties": { "ID": "31MA", "TOWN": "BELCHERTOWN", "AIRPORT_NA": "NORM'S FIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 15 43", "LONGITUDE": "72 24 29", "ELEVATION": 460, "P_LENGTH": 1300.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.408257, 42.261722 ] } }
,
{ "type": "Feature", "id": 27, "properties": { "ID": "13MA", "TOWN": "PALMER", "AIRPORT_NA": "METROPOLITAN", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 13 24", "LONGITUDE": "72 18 41", "ELEVATION": 418, "P_LENGTH": 2475.000000, "S_LENGTH": 0, "P_WIDTH": 55, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "LIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.311290, 42.223565 ] } }
,
{ "type": "Feature", "id": 28, "properties": { "ID": "ORE", "TOWN": "ORANGE", "AIRPORT_NA": "ORANGE MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-1", "RUNWAY": 2, "LATITUDE": "42 34 04", "LONGITUDE": "72 17 28", "ELEVATION": 555, "P_LENGTH": 5000.000000, "S_LENGTH": 4999, "P_WIDTH": 75, "S_WIDTH": 150, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "NOT WORKING", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.286258, 42.571762 ] } }
,
{ "type": "Feature", "id": 29, "properties": { "ID": "MA53", "TOWN": "WARE", "AIRPORT_NA": "WARE", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 16 55", "LONGITUDE": "72 12 53", "ELEVATION": 483, "P_LENGTH": 2030.000000, "S_LENGTH": 0, "P_WIDTH": 150, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.214962, 42.284138 ] } }
,
{ "type": "Feature", "id": 30, "properties": { "ID": "GDM", "TOWN": "GARDNER", "AIRPORT_NA": "GARDNER MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-1", "RUNWAY": 1, "LATITUDE": "42 33 00", "LONGITUDE": "72 01 00", "ELEVATION": 955, "P_LENGTH": 3000.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.016339, 42.550883 ] } }
,
{ "type": "Feature", "id": 31, "properties": { "ID": "3B0", "TOWN": "SOUTHBRIDGE", "AIRPORT_NA": "SOUTHBRIDGE MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-2", "RUNWAY": 2, "LATITUDE": "42 06 03", "LONGITUDE": "72 02 20", "ELEVATION": 697, "P_LENGTH": 3500.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.038910, 42.100796 ] } }
,
{ "type": "Feature", "id": 32, "properties": { "ID": "MA30", "TOWN": "CHARLTON", "AIRPORT_NA": "DRESSER HILL", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 06 00", "LONGITUDE": "71 57 58", "ELEVATION": 810, "P_LENGTH": 2000.000000, "S_LENGTH": 0, "P_WIDTH": 300, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.969495, 42.103114 ] } }
,
{ "type": "Feature", "id": 33, "properties": { "ID": "8B5", "TOWN": "BARRE", "AIRPORT_NA": "TANNER-HILLER", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 21 15", "LONGITUDE": "72 07 45", "ELEVATION": 584, "P_LENGTH": 3064.000000, "S_LENGTH": 0, "P_WIDTH": 40, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -72.128820, 42.357286 ] } }
,
{ "type": "Feature", "id": 34, "properties": { "ID": "MA89", "TOWN": "NEW BRAINTREE", "AIRPORT_NA": "B&B FARM", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 20 46", "LONGITUDE": "72 06 14", "ELEVATION": 980, "P_LENGTH": 2000.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -72.103464, 42.345070 ] } }
,
{ "type": "Feature", "id": 35, "properties": { "ID": "MA08", "TOWN": "OXFORD", "AIRPORT_NA": "OXFORD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 09 07", "LONGITUDE": "71 50 08", "ELEVATION": 763, "P_LENGTH": 2047.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.835255, 42.150347 ] } }
,
{ "type": "Feature", "id": 36, "properties": { "ID": "MA97", "TOWN": "SUTTON", "AIRPORT_NA": "WATERS", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 07 30", "LONGITUDE": "71 44 23", "ELEVATION": 700, "P_LENGTH": 2400.000000, "S_LENGTH": 0, "P_WIDTH": 60, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.739109, 42.125755 ] } }
,
{ "type": "Feature", "id": 37, "properties": { "ID": "MA10", "TOWN": "SPENCER", "AIRPORT_NA": "SPENCER AIRPORT", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 17 30", "LONGITUDE": "71 57 45", "ELEVATION": 1040, "P_LENGTH": 1930.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.964704, 42.289709 ] } }
,
{ "type": "Feature", "id": 38, "properties": { "ID": "ORH", "TOWN": "WORCESTER", "AIRPORT_NA": "WORCESTER REGIONAL", "OWNER_TYPE": "MassPort", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 2, "LATITUDE": "42 16 02", "LONGITUDE": "71 52 33", "ELEVATION": 1009, "P_LENGTH": 7000.000000, "S_LENGTH": 5000, "P_WIDTH": 150, "S_WIDTH": 100, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT-GROOVED", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "FAA", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -71.872483, 42.267815 ] } }
,
{ "type": "Feature", "id": 39, "properties": { "ID": "MA16", "TOWN": "HOLDEN", "AIRPORT_NA": "MARSHALL'S", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 21 48", "LONGITUDE": "71 49 18", "ELEVATION": 630, "P_LENGTH": 1700.000000, "S_LENGTH": 0, "P_WIDTH": 800, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.822572, 42.363092 ] } }
,
{ "type": "Feature", "id": 40, "properties": { "ID": "3B3", "TOWN": "STERLING", "AIRPORT_NA": "STERLING", "OWNER_TYPE": "Public", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 25 30", "LONGITUDE": "71 47 30", "ELEVATION": 459, "P_LENGTH": 3100.000000, "S_LENGTH": 0, "P_WIDTH": 40, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "NONE", "S_RUNWAYLI": "", "CONTROLTOW": "", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.793510, 42.426420 ] } }
,
{ "type": "Feature", "id": 41, "properties": { "ID": "61MA", "TOWN": "SHIRLEY", "AIRPORT_NA": "SHIRLEY", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 31 37", "LONGITUDE": "71 39 52", "ELEVATION": 400, "P_LENGTH": 1700.000000, "S_LENGTH": 0, "P_WIDTH": 60, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.664565, 42.528547 ] } }
,
{ "type": "Feature", "id": 42, "properties": { "ID": "1B6", "TOWN": "HOPEDALE", "AIRPORT_NA": "HOPEDALE INDUSTRIAL AIRPARK", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "BU-1", "RUNWAY": 1, "LATITUDE": "42 06 25", "LONGITUDE": "71 30 40", "ELEVATION": 269, "P_LENGTH": 3172.000000, "S_LENGTH": 0, "P_WIDTH": 90, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.509375, 42.104218 ] } }
,
{ "type": "Feature", "id": 43, "properties": { "ID": "MA19", "TOWN": "BERLIN", "AIRPORT_NA": "BERLIN LANDING AREA", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 22 03", "LONGITUDE": "71 38 30", "ELEVATION": 270, "P_LENGTH": 3000.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.642747, 42.367646 ] } }
,
{ "type": "Feature", "id": 44, "properties": { "ID": "26MA", "TOWN": "PEPPERELL", "AIRPORT_NA": "PEPPERELL", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 41 46", "LONGITUDE": "71 33 00", "ELEVATION": 176, "P_LENGTH": 2820.000000, "S_LENGTH": 0, "P_WIDTH": 25, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.552951, 42.693777 ] } }
,
{ "type": "Feature", "id": 45, "properties": { "ID": "6B6", "TOWN": "STOW", "AIRPORT_NA": "MINUTEMAN AIRFIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "BU-2", "RUNWAY": 2, "LATITUDE": "42 25 30", "LONGITUDE": "71 31 00", "ELEVATION": 268, "P_LENGTH": 2770.000000, "S_LENGTH": 1600, "P_WIDTH": 48, "S_WIDTH": 70, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "LIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "RELIEVER GA", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.518352, 42.461791 ] } }
,
{ "type": "Feature", "id": 46, "properties": { "ID": "MA52", "TOWN": "MAYNARD", "AIRPORT_NA": "SIDS", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 26 18", "LONGITUDE": "71 27 58", "ELEVATION": 220, "P_LENGTH": 1075.000000, "S_LENGTH": 0, "P_WIDTH": 30, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.470051, 42.438093 ] } }
,
{ "type": "Feature", "id": 47, "properties": { "ID": "9B1", "TOWN": "MARLBOROUGH", "AIRPORT_NA": "MARLBORO", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 20 30", "LONGITUDE": "71 30 39", "ELEVATION": 285, "P_LENGTH": 1676.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.509736, 42.343523 ] } }
,
{ "type": "Feature", "id": 48, "properties": { "ID": "09MA", "TOWN": "SOUTHBOROUGH", "AIRPORT_NA": "KALLANDER FIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "42 18 15", "LONGITUDE": "71 30 21", "ELEVATION": 403, "P_LENGTH": 2000.000000, "S_LENGTH": 1700, "P_WIDTH": 100, "S_WIDTH": 50, "P_SURFACET": "ASPHALT", "S_SURFACET": "TURF", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.505321, 42.305116 ] } }
,
{ "type": "Feature", "id": 49, "properties": { "ID": "MA70", "TOWN": "SUDBURY", "AIRPORT_NA": "SUDBURY", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 21 03", "LONGITUDE": "71 25 47", "ELEVATION": 135, "P_LENGTH": 1000.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.428964, 42.351695 ] } }
,
{ "type": "Feature", "id": 50, "properties": { "ID": "LWM", "TOWN": "LAWRENCE", "AIRPORT_NA": "LAWRENCE MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-2", "RUNWAY": 2, "LATITUDE": "42 43 02", "LONGITUDE": "71 07 26", "ELEVATION": 148, "P_LENGTH": 5000.000000, "S_LENGTH": 3900, "P_WIDTH": 150, "S_WIDTH": 100, "P_SURFACET": "ASPHALT-MICROSURFACE", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "RELIEVER GA", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.121826, 42.717538 ] } }
,
{ "type": "Feature", "id": 51, "properties": { "ID": "MA36", "TOWN": "IPSWICH", "AIRPORT_NA": "SNOW", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 39 59", "LONGITUDE": "70 51 11", "ELEVATION": 61, "P_LENGTH": 1600.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.852900, 42.666718 ] } }
,
{ "type": "Feature", "id": 52, "properties": { "ID": "BVY", "TOWN": "BEVERLY", "AIRPORT_NA": "BEVERLY MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-2", "RUNWAY": 2, "LATITUDE": "42 35 03", "LONGITUDE": "70 55 03", "ELEVATION": 108, "P_LENGTH": 5001.000000, "S_LENGTH": 4637, "P_WIDTH": 150, "S_WIDTH": 100, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "RELIEVER GA", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.917683, 42.585138 ] } }
,
{ "type": "Feature", "id": 53, "properties": { "ID": "BED", "TOWN": "BEDFORD", "AIRPORT_NA": "HANSCOM FIELD", "OWNER_TYPE": "MassPort", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 2, "LATITUDE": "42 28 12", "LONGITUDE": "71 17 22", "ELEVATION": 133, "P_LENGTH": 7001.000000, "S_LENGTH": 5106, "P_WIDTH": 150, "S_WIDTH": 150, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "FAA", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "RELIEVER W\/ COMMERCIAL SERVICE", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -71.289290, 42.470782 ] } }
,
{ "type": "Feature", "id": 54, "properties": { "ID": "1B9", "TOWN": "MANSFIELD", "AIRPORT_NA": "MANSFIELD MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 2, "LATITUDE": "42 00 15", "LONGITUDE": "71 12 00", "ELEVATION": 122, "P_LENGTH": 3498.000000, "S_LENGTH": 2317, "P_WIDTH": 75, "S_WIDTH": 100, "P_SURFACET": "ASPHALT", "S_SURFACET": "TURF", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.200992, 42.002769 ] } }
,
{ "type": "Feature", "id": 55, "properties": { "ID": "TAN", "TOWN": "TAUNTON", "AIRPORT_NA": "KING FIELD", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 1, "LATITUDE": "41 52 45", "LONGITUDE": "71 01 15", "ELEVATION": 43, "P_LENGTH": 3500.000000, "S_LENGTH": 1900, "P_WIDTH": 75, "S_WIDTH": 60, "P_SURFACET": "ASPHALT", "S_SURFACET": "TURF", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "NONE", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.015430, 41.873083 ] } }
,
{ "type": "Feature", "id": 56, "properties": { "ID": "1M8", "TOWN": "BERKLEY", "AIRPORT_NA": "MYRICKS", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 50 20", "LONGITUDE": "71 01 33", "ELEVATION": 71, "P_LENGTH": 2150.000000, "S_LENGTH": 0, "P_WIDTH": 150, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.026887, 41.838959 ] } }
,
{ "type": "Feature", "id": 57, "properties": { "ID": "5MA9", "TOWN": "WESTPORT", "AIRPORT_NA": "ALLEN'S POND", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "41 30 40", "LONGITUDE": "71 01 41", "ELEVATION": 60, "P_LENGTH": 1550.000000, "S_LENGTH": 1150, "P_WIDTH": 40, "S_WIDTH": 40, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.026310, 41.509773 ] } }
,
{ "type": "Feature", "id": 58, "properties": { "ID": "3MA5", "TOWN": "WESTPORT", "AIRPORT_NA": "WESTPORT", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 32 35", "LONGITUDE": "71 02 07", "ELEVATION": 80, "P_LENGTH": 2150.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.034933, 41.542530 ] } }
,
{ "type": "Feature", "id": 59, "properties": { "ID": "3B2", "TOWN": "MARSHFIELD", "AIRPORT_NA": "MARSHFIELD MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "BU-2", "RUNWAY": 1, "LATITUDE": "42 05 53", "LONGITUDE": "70 40 21", "ELEVATION": 11, "P_LENGTH": 2999.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.672804, 42.097774 ] } }
,
{ "type": "Feature", "id": 60, "properties": { "ID": "MA64", "TOWN": "PEMBROKE", "AIRPORT_NA": "PHEASANT FIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 04 31", "LONGITUDE": "70 48 55", "ELEVATION": 40, "P_LENGTH": 2000.000000, "S_LENGTH": 0, "P_WIDTH": 150, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "EMERGENCY USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.815191, 42.074502 ] } }
,
{ "type": "Feature", "id": 61, "properties": { "ID": "MA63", "TOWN": "PEMBROKE", "AIRPORT_NA": "SHERMAN-PRIVATE", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 04 26", "LONGITUDE": "70 47 53", "ELEVATION": 34, "P_LENGTH": 1500.000000, "S_LENGTH": 0, "P_WIDTH": 50, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.797113, 42.073756 ] } }
,
{ "type": "Feature", "id": 62, "properties": { "ID": "MA02", "TOWN": "HANSON", "AIRPORT_NA": "CRANLAND", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "42 01 29", "LONGITUDE": "70 50 19", "ELEVATION": 71, "P_LENGTH": 1845.000000, "S_LENGTH": 0, "P_WIDTH": 60, "S_WIDTH": 0, "P_SURFACET": "GRAVEL", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.837783, 42.024239 ] } }
,
{ "type": "Feature", "id": 63, "properties": { "ID": "PVC", "TOWN": "PROVINCETOWN", "AIRPORT_NA": "PROVINCETOWN MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-1", "RUNWAY": 1, "LATITUDE": "42 04 19", "LONGITUDE": "70 13 19", "ELEVATION": 8, "P_LENGTH": 3498.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.215912, 42.074388 ] } }
,
{ "type": "Feature", "id": 64, "properties": { "ID": "PYM", "TOWN": "PLYMOUTH", "AIRPORT_NA": "PLYMOUTH MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-2", "RUNWAY": 2, "LATITUDE": "41 54 45", "LONGITUDE": "70 43 35", "ELEVATION": 149, "P_LENGTH": 4350.000000, "S_LENGTH": 3350, "P_WIDTH": 75, "S_WIDTH": 75, "P_SURFACET": "ASPHALT", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "MIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "Y", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.729879, 41.910249 ] } }
,
{ "type": "Feature", "id": 65, "properties": { "ID": "11MA", "TOWN": "WAREHAM", "AIRPORT_NA": "BULLJUMP", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 48 26", "LONGITUDE": "70 45 30", "ELEVATION": 60, "P_LENGTH": 1200.000000, "S_LENGTH": 0, "P_WIDTH": 42, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.758522, 41.807938 ] } }
,
{ "type": "Feature", "id": 66, "properties": { "ID": "HYA", "TOWN": "HYANNIS", "AIRPORT_NA": "BARNSTABLE MUNICIPAL", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "TRAN", "RUNWAY": 3, "LATITUDE": "41 40 07", "LONGITUDE": "70 16 48", "ELEVATION": 52, "P_LENGTH": 5425.000000, "S_LENGTH": 5252, "P_WIDTH": 150, "S_WIDTH": 150, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALY-GROOVED", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "HIRLS", "CONTROLTOW": "FAA", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -70.282796, 41.666647 ] } }
,
{ "type": "Feature", "id": 67, "properties": { "ID": "2B1", "TOWN": "MARSTONS MILLS", "AIRPORT_NA": "CAPE COD", "OWNER_TYPE": "Public", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 3, "LATITUDE": "41 41 15", "LONGITUDE": "70 24 15", "ELEVATION": 100, "P_LENGTH": 1901.000000, "S_LENGTH": 1128, "P_WIDTH": 60, "S_WIDTH": 60, "P_SURFACET": "TURF", "S_SURFACET": "TURF", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.401302, 41.685133 ] } }
,
{ "type": "Feature", "id": 68, "properties": { "ID": "5B6", "TOWN": "FALMOUTH", "AIRPORT_NA": "FALMOUTH AIRPARK", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "LU", "RUNWAY": 1, "LATITUDE": "41 35 05", "LONGITUDE": "70 32 30", "ELEVATION": 43, "P_LENGTH": 2300.000000, "S_LENGTH": 0, "P_WIDTH": 40, "S_WIDTH": 0, "P_SURFACET": "", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.542383, 41.584362 ] } }
,
{ "type": "Feature", "id": 69, "properties": { "ID": "MA44", "TOWN": "OAK BLUFFS", "AIRPORT_NA": "TRADE WIND", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "41 26 30", "LONGITUDE": "70 34 13", "ELEVATION": 43, "P_LENGTH": 2200.000000, "S_LENGTH": 2200, "P_WIDTH": 200, "S_WIDTH": 200, "P_SURFACET": "TURF", "S_SURFACET": "TURF", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.568217, 41.440873 ] } }
,
{ "type": "Feature", "id": 70, "properties": { "ID": "MVY", "TOWN": "MARTHA'S VINEYARD", "AIRPORT_NA": "MARTHA'S VINEYARD", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "GU-2", "RUNWAY": 3, "LATITUDE": "41 23 34", "LONGITUDE": "70 36 57", "ELEVATION": 68, "P_LENGTH": 5500.000000, "S_LENGTH": 3297, "P_WIDTH": 100, "S_WIDTH": 75, "P_SURFACET": "ASPHALT-GROOVED", "S_SURFACET": "ASPHALT", "P_RUNWAYLI": "HIRLS", "S_RUNWAYLI": "MIRLS", "CONTROLTOW": "CONTRACT", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "COMMERCIAL SERVICE PRIMARY", "AIRSERVICE": "Y" }, "geometry": { "type": "Point", "coordinates": [ -70.614815, 41.390617 ] } }
,
{ "type": "Feature", "id": 71, "properties": { "ID": "1B2", "TOWN": "EDGARTOWN", "AIRPORT_NA": "KATAMA AIRPARK", "OWNER_TYPE": "Public", "FACILITY_T": "PUBLIC OWNED AP", "CLASS": "LU", "RUNWAY": 4, "LATITUDE": "41 21 30", "LONGITUDE": "70 31 30", "ELEVATION": 20, "P_LENGTH": 4000.000000, "S_LENGTH": 2700, "P_WIDTH": 50, "S_WIDTH": 50, "P_SURFACET": "TURF", "S_SURFACET": "TURF", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "Y", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.522100, 41.356954 ] } }
,
{ "type": "Feature", "id": 72, "properties": { "ID": "MA55", "TOWN": "NANTUCKET", "AIRPORT_NA": "MUSKEGET ISLAND", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "41 20 05", "LONGITUDE": "70 17 58", "ELEVATION": 90, "P_LENGTH": 1820.000000, "S_LENGTH": 0, "P_WIDTH": 100, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.294507, 41.333131 ] } }
,
{ "type": "Feature", "id": 73, "properties": { "ID": "MA72", "TOWN": "NANTUCKET", "AIRPORT_NA": "TUCKERNECK", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "41 17 51", "LONGITUDE": "70 15 37", "ELEVATION": 23, "P_LENGTH": 2000.000000, "S_LENGTH": 2000, "P_WIDTH": 20, "S_WIDTH": 20, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -70.259762, 41.297349 ] } }
,
{ "type": "Feature", "id": 74, "properties": { "ID": "MA75", "TOWN": "UXBRIDGE", "AIRPORT_NA": "SKY GLEN", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 02 27", "LONGITUDE": "71 36 58", "ELEVATION": 260, "P_LENGTH": 2400.000000, "S_LENGTH": 0, "P_WIDTH": 75, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.616014, 42.040843 ] } }
,
{ "type": "Feature", "id": 75, "properties": { "ID": "08MA", "TOWN": "SOUTHBOROUGH", "AIRPORT_NA": "WORMID", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 17 38", "LONGITUDE": "71 29 46", "ELEVATION": 360, "P_LENGTH": 1000.000000, "S_LENGTH": 0, "P_WIDTH": 18, "S_WIDTH": 0, "P_SURFACET": "TURF", "S_SURFACET": "", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.495788, 42.294186 ] } }
,
{ "type": "Feature", "id": 76, "properties": { "ID": "1MA5", "TOWN": "SOUTHBOROUGH", "AIRPORT_NA": "UNKNOWN FIELD", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 1, "LATITUDE": "42 16 44", "LONGITUDE": "71 32 52", "ELEVATION": 432, "P_LENGTH": 1500.000000, "S_LENGTH": 0, "P_WIDTH": 30, "S_WIDTH": 0, "P_SURFACET": "ASPHALT", "S_SURFACET": "", "P_RUNWAYLI": "LIRLS", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "", "RENTALCAR": "", "SERVICELEV": "PRIVATE USE", "AIRSERVICE": "" }, "geometry": { "type": "Point", "coordinates": [ -71.543864, 42.279009 ] } }
,
{ "type": "Feature", "id": 77, "properties": { "ID": "MA2", "TOWN": "METHUEN", "AIRPORT_NA": "MERRIMACK VALLEY SEAPLANE BASE", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "42 42 00", "LONGITUDE": "71 12 58", "ELEVATION": 50, "P_LENGTH": 5000.000000, "S_LENGTH": 4700, "P_WIDTH": 500, "S_WIDTH": 250, "P_SURFACET": "WATER", "S_SURFACET": "WATER", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -71.215363, 42.702552 ] } }
,
{ "type": "Feature", "id": 78, "properties": { "ID": "MA6", "TOWN": "HALIFAX", "AIRPORT_NA": "MONPONSETT POND SEAPLANE BASE", "OWNER_TYPE": "Private", "FACILITY_T": "PRIVATE OWNED AP", "CLASS": "", "RUNWAY": 2, "LATITUDE": "42 00 35", "LONGITUDE": "70 50 35", "ELEVATION": 52, "P_LENGTH": 5000.000000, "S_LENGTH": 3200, "P_WIDTH": 500, "S_WIDTH": 300, "P_SURFACET": "WATER", "S_SURFACET": "WATER", "P_RUNWAYLI": "", "S_RUNWAYLI": "", "CONTROLTOW": "N", "RESTAURANT": "N", "RENTALCAR": "", "SERVICELEV": "GENERAL AVIATION", "AIRSERVICE": "N" }, "geometry": { "type": "Point", "coordinates": [ -70.843448, 42.009153 ] } }

]
}
